### PR TITLE
Fix #180 Fix # 181 -  Runner config to respect bundle's configured path + use nproc instead of defaulting to num_parallel = 2

### LINKED ISSUE #180: Handle of bundle path is weird
https://github.com/NREL/openstudio-extension-gem/blob/bb25c593c6fd3eab214ec92d7d1d5e7625937e2e/lib/openstudio/extension/runner.rb#L64

https://github.com/NREL/openstudio-extension-gem/blob/bb25c593c6fd3eab214ec92d7d1d5e7625937e2e/lib/openstudio/extension/runner.rb#L102-L109

https://github.com/NREL/openstudio-extension-gem/blob/bb25c593c6fd3eab214ec92d7d1d5e7625937e2e/lib/openstudio/extension/runner.rb#L127-L131

Instead of overwritting the bundle path **I chose to specify to bundle** (via `bundle install --path=.bundle` or running `bundle config --local path .bundle` with the value you thing I want `.bundle/install`, you should take for granted the bundle config one.

### LINKED ISSUE #181: Change default config to use nproc instead of harcoding to 2 parallel runs
https://github.com/NREL/openstudio-extension-gem/blob/bb25c593c6fd3eab214ec92d7d1d5e7625937e2e/lib/openstudio/extension/runner_config.rb#L49

You already use Parallel gem, use `Parallel.physical_processor_count` or `Parallel.processor_count`

### PR DESCRIPTION
**Pull request by jmarrec**
* Fix #180 
* Fix #181
* DO not try to add copyright to the vendor/ directory (when `bundle config --local deployment true` is used, this is where it goes, and ruby/setup-ruby GHA action with caching does that)

### CODE REVIEW

File: lib/openstudio/extension/runner_config.rb [hunk 1]
```diff
@@ -40,17 +42,31 @@ def add_config_option(name, value)
...
+
+        if (bundle_install_path = bundler_settings.path.explicit_path)
+          puts "Defaulting bundle_install_path to bundle's local config value: '#{bundle_install_path}'"
+        else
+          puts "Defaulting to .bundle/install (and ignoring system wide: Bundler.configured_bundle_path.base_path=#{bundler_settings.path.base_path})"
+          bundle_install_path = File.join(dirname, '.bundle/install/')
+        end
+
+        return bundle_install_path
+      end
```
Comment (jmarrec) [inline lib/openstudio/extension/runner_config.rb:57]: Infer the bundle_install_path if we can find a .bundle/config file

File: lib/openstudio/extension/runner_config.rb [hunk 2]
```diff
@@ -40,17 +42,31 @@ def add_config_option(name, value)
...
         return {
           file_version: '0.1.0',
           max_datapoints: 1E9.to_i,
-          num_parallel: 2,
+          num_parallel: Parallel.processor_count,
           run_simulations: true,
           verbose: false,
           gemfile_path: '',
-          bundle_install_path: ''
+          bundle_install_path: get_local_bundle_config_path(dirname),
```
Comment (jmarrec) [inline lib/openstudio/extension/runner_config.rb:69]: use that + default num_parallel to available (nproc)

File: lib/openstudio/extension/runner_config.rb [hunk 3]
```diff
@@ -60,11 +76,18 @@ def self.default_config
...
+          puts File.read(runner_conf_file)
+        end
+
+        config = default_config(dirname)
+        File.open(runner_conf_file, 'w') do |f|
+          f << JSON.pretty_generate(config)
         end
 
-        return default_config
+        return config
```
Comment (jmarrec) [inline lib/openstudio/extension/runner_config.rb:90]: Warn when overwritting runner.conf and print previous so one can revert manually if needed

File: lib/openstudio/extension/runner.rb [hunk 4]
```diff
@@ -41,13 +41,14 @@ def initialize(dirname = Dir.pwd, bundle_without = [], options = {})
 
         # if the dirname contains a runner.conf file, then use the config file to specify the parameters
 
-        @options = OpenStudio::Extension::RunnerConfig.default_config
+        @options = OpenStudio::Extension::RunnerConfig.default_config(dirname)
```
Comment (jmarrec) [inline lib/openstudio/extension/runner.rb:44]: Default config will have the bundle config path or the default .bundle/install already

File: lib/openstudio/extension/runner.rb [hunk 5]
```diff
@@ -41,13 +41,14 @@ def initialize(dirname = Dir.pwd, bundle_without = [], options = {})
...
         # ORDER of PRECEDENCE: default config < runner.conf file < options passed in directly
         if File.exist?(File.join(dirname, OpenStudio::Extension::RunnerConfig::FILENAME))
           puts 'Using runner options from runner.conf file'
           runner_config = OpenStudio::Extension::RunnerConfig.new(dirname)
-          # use the default values overriden with runner.conf values
-          @options = @options.merge(runner_config.options)
+          # use the default values overriden with runner.conf values where not
+          # nil nor empty strings
+          @options = @options.merge(runner_config.options.reject{|k, v| v.nil? || (v.kind_of?(String) && v === '')})
```
Comment (jmarrec) [inline lib/openstudio/extension/runner.rb:51]: Reject empty (nil or empty strings) from runner.conf when merging.

Comment (jmarrec) [reply lib/openstudio/extension/runner.rb:51]: Note that line 65 is technically not needed anymore now... but I was wary of removing it

File: lib/openstudio/extension/runner.rb [hunk 6]
```diff
@@ -99,12 +100,12 @@ def initialize(dirname = Dir.pwd, bundle_without = [], options = {})
...
-            if File.exist?('./.bundle/config') # checking wrt gemfile_dir
-              puts 'config exists'
+            if conf_bpath = Bundler.configured_bundle_path.explicit_path
+              puts 'bundler config exists'
               needs_config = false
-              config = YAML.load_file('./.bundle/config')
 
-              if config['BUNDLE_PATH'] != @bundle_install_path
+              if conf_bpath != @bundle_install_path
+                raise "Detected mistmatch between bundle's configured path #{conf_bpath} and runner configuration #{@bundle_install_path}"
```
Comment (jmarrec) [inline lib/openstudio/extension/runner.rb:108]: Now that it respects the configured path, just throw if they don't match. User will have to either trash the runner.conf or adjust it.

File: spec/openstudio/runner_config_spec.rb [hunk 7]
```diff
@@ -4,32 +4,52 @@
...
+
 RSpec.describe OpenStudio::Extension::RunnerConfig do
-  before :all do
-    if File.exist? 'runner.conf'
-      puts 'removing runner conf'
-      File.delete('runner.conf')
+  before :each do
+    @test_folder = File.join(File.dirname(__FILE__), "test_defaults")
+    if File.exist?(@test_folder)
+      FileUtils.rm_rf(@test_folder)
```
Comment (jmarrec) [inline spec/openstudio/runner_config_spec.rb:13]: changed the entire spec to use a throwaway folder instead of messing with the root of the repo.

File: spec/openstudio/runner_config_spec.rb [hunk 8]
```diff
@@ -4,32 +4,52 @@
...
   it 'has defaults' do
-    defaults = OpenStudio::Extension::RunnerConfig.default_config
+    defaults = OpenStudio::Extension::RunnerConfig.default_config(@test_folder)
+    expect(defaults[:max_datapoints]).to eq 1E9.to_i
+    expect(defaults[:num_parallel]).to eq Parallel.processor_count
+    expect(defaults[:run_simulations]).to eq true
+    expect(defaults[:verbose]).to eq false
+    expect(defaults[:gemfile_path]).to eq ''
+    expect(defaults[:bundle_install_path]).to eq File.join(@test_folder, '.bundle/install/')
+  end
```
Comment (jmarrec) [inline spec/openstudio/runner_config_spec.rb:27]: Tests normal defaults

File: spec/openstudio/runner_config_spec.rb [hunk 9]
```diff
@@ -4,32 +4,52 @@
...
+    File.write(File.join(@test_folder, 'Gemfile'), "source 'http://rubygems.org'")
+    defaults = OpenStudio::Extension::RunnerConfig.default_config(@test_folder)
     expect(defaults[:max_datapoints]).to eq 1E9.to_i
-    expect(defaults[:num_parallel]).to eq 2
+    expect(defaults[:num_parallel]).to eq Parallel.processor_count
     expect(defaults[:run_simulations]).to eq true
     expect(defaults[:verbose]).to eq false
     expect(defaults[:gemfile_path]).to eq ''
-    expect(defaults[:bundle_install_path]).to eq ''
+    expect(defaults[:bundle_install_path]).to eq 'mycustom_bundle'
```
Comment (jmarrec) [inline spec/openstudio/runner_config_spec.rb:40]: Tests respecting the bundle config

File: lib/openstudio/extension/runner_config.rb (hunk 2 above)
Comment (nllong) [reply lib/openstudio/extension/runner_config.rb:69]: maybe `processor_count - 1` ?

File: lib/openstudio/extension/runner_config.rb (hunk 3 above)
Comment (nllong) [reply lib/openstudio/extension/runner_config.rb:90]: I'd suggest writing out the previous config to a file... save to `.backup` or `.previous`

**Review by nllong — CHANGES_REQUESTED** [review]
nice updates... I can test in more depth post Mar 20... but I don't see any major issues. I have two comments that should be addressed.

File: lib/openstudio/extension/runner_config.rb (hunk 2 above)
Comment (jmarrec) [reply lib/openstudio/extension/runner_config.rb:69]: Meh, I understand the rationale. But I really doubt the ruby thread is going to use resources while the rest is doing what it has to do (it's blocking if I reminder correctly). While on my machine with 16 threads I'd be totally ok with a spare thread, on GHA where you have 2 or 3 total this might be a waste?

File: lib/openstudio/extension/runner_config.rb [hunk 10]
```diff
@@ -40,17 +43,31 @@ def add_config_option(name, value)
...
+
       ##
       # Return the default runner configuration
-      def self.default_config
+      def self.default_config(dirname)
         return {
           file_version: '0.1.0',
           max_datapoints: 1E9.to_i,
-          num_parallel: 2,
+          num_parallel: Parallel.processor_count - 1,
```
Comment (jmarrec) [inline lib/openstudio/extension/runner_config.rb:66]:
```suggestion
          num_parallel: Parallel.processor_count,
```

If we want to revert back to using all threads

File: lib/openstudio/extension/runner_config.rb (hunk 2 above)
Comment (jmarrec) [reply lib/openstudio/extension/runner_config.rb]: I went ahead and did it in fbc2936bcc38e6659972a34cc3ece3677fa328dc

File: lib/openstudio/extension/runner_config.rb [hunk 11]
```diff
@@ -3,13 +3,18 @@
...
+require 'fileutils'
 require 'json'
+require 'parallel'
 
 module OpenStudio
   module Extension
     class RunnerConfig
       FILENAME = 'runner.conf'.freeze
 
+      DEFAULT_NPROC = Parallel.processor_count - 1
```
Comment (jmarrec) [inline lib/openstudio/extension/runner_config.rb:16]:
```suggestion
      DEFAULT_NPROC = Parallel.processor_count
```

If you feel like reverting to using all threads
