### PR TITLE
fixing option merging bug

### LINKED ISSUE #96: Runner.conf options merge bug
There is a bug when trying to use both a runner.conf file and pass in options.  the options wipe out the runner.conf file

### PR DESCRIPTION
**Pull request by kflemin**
Fixes #96

### CODE REVIEW

File: lib/openstudio/extension/runner.rb [hunk 1]
```diff
@@ -73,15 +73,18 @@ def initialize(dirname = Dir.pwd, bundle_without = [], options = {})
...
           puts 'Using runner options from runner.conf file'
           runner_config = OpenStudio::Extension::RunnerConfig.new(dirname)
           # use the default values overriden with runner.conf values
           @options = @options.merge(runner_config.options)
         end
 
-        # use the passed values or defaults overriden by passed options
-        @options = @options.merge(options)
+        if !options.empty?
+          puts 'Merging in passed in options'
```
Comment (nllong) [inline lib/openstudio/extension/runner.rb:84]:
```suggestion
          puts 'Merging in passed-in options'
```

**Review by nllong — APPROVED** [review]
Fantastic... nice catch. I updated the changelog.
